server:
  port: 8084
spring:
  application:
    name: person
  r2dbc:
      url: r2dbc:postgresql://localhost:5432/person
      username: postgres
      password: root
  sql:
    init:
      mode:
      schema-locations: classpath:schema.sql
  logging:
    level:
      org.springframework.web.reactive.function.server: DEBUG

application:
  security:
    jwt:
      secret-key: m2yrnAnikqppG3cqmTOGXExVuVlLxOvaN5q2Gqwel/aigX+wgP68HvbE1ypcpUBv
      expiration: 86400000
